name: ttct_full
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch=2.7.1
  - torchvision
  - pytorch-lightning=2.5.2
  - fastapi
  - uvicorn
  - python-multipart
  - pillow
  - pip
  - pip:
      # any pip-only extras here if needed
